DROP TABLE IF EXISTS task_run;

CREATE TABLE task_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(100) NOT NULL,
    shop_id VARCHAR(100) NOT NULL,
    platform VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP(6) NOT NULL,
    finished_at TIMESTAMP(6),
    row_count BIGINT NOT NULL,
    error_message TEXT,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_task_run_task_id UNIQUE (task_id)
);

CREATE INDEX idx_task_run_shop_status_updated
    ON task_run (shop_id, status, updated_at, id);
